### ISSUE TITLE
Unable to use custom svgoOptions

### ISSUE THREAD

**Issue by vaskulikov1983** [rodshtein/sveltekit-sprite#2]
### Describe the bug

In the plugin settings we can set params for svgoOptions:

```javascript 
sveltekitSprite({
  svgoOptions: {
    presetDefault: true,
    ... other option here
  },
}),
```
My, for example, look like this:
```javascript 
sveltekitSprite({
  svgoOptions: {
        multipass: true,
        plugins: [
          'preset-default',
          'convertStyleToAttrs',
          { name: 'removeAttrs', params: { attrs: '(fill|stroke)' } }
        ]
      }
}),
```
And here is the problem: Custom options will never use to compile svg-sprite. It's happens because in index.mjs on line:97 we can see this:

```javascript
  svgoOptions = { ...svgoOptions, ...mandatorySvgoOptions };
```
So _mandatorySvgoOptions.plugins_ will always rewrite _svgoOptions.plugins_. And user like me will not be able to manage the compiling svgo-process.

**Comment by rodshtein** [comment]
Fixed in 6394ccefa7033b9ef2f81e1860bce3d24218062e
